/* ============================================================
   CATEGORIES
   ============================================================ */
var LEVELS = {
  1:{name:"Les Légendes",        sub:"Jordan, Kobe, Magic, Shaq...",        color:"#552583", sym:"★"},
  2:{name:"Les Stars d'aujourd'hui", sub:"LeBron, Curry, Giannis, Jokic...", color:"#1d428a", sym:"⚡"},
  3:{name:"Les Français en NBA", sub:"Wembanyama, Parker, Gobert...",       color:"#0055a4", sym:"FR"},
  4:{name:"La NBA",              sub:"Équipes, règles et trophées",        color:"#c8102e", sym:"NBA"}
};
var LEVEL_ORDER=[1,2,3,4];

/* ============================================================
   BANQUE DE QUESTIONS
   level : 1=Légendes | 2=Stars | 3=Français | 4=La NBA
   hint  = le secret du coach (indice)
   ============================================================ */
var BANK = [

  /* ===================== LES LÉGENDES ===================== */
  { level:1, theme:"Michael Jordan", rule:"Les titres",
    scene: function(){return sceneTrophy("Combien de trophées ?");},
    q:"Combien de titres de champion NBA Michael Jordan a-t-il gagnés avec les Chicago Bulls ?",
    choices:["6","2","10","1"], correct:0,
    hint:"Autant que les faces d'un dé !",
    explain:"Jordan a gagné 6 titres avec les Bulls : trois d'affilée (1991, 1992, 1993) puis encore trois d'affilée (1996, 1997, 1998). Et il a été élu meilleur joueur des Finales les 6 fois !" },
  { level:1, theme:"Michael Jordan", rule:"Le maillot",
    scene: function(){return sceneJersey("#ce1141","#000000","?","Quel numéro ?");},
    q:"Quel numéro de maillot est devenu célèbre grâce à Michael Jordan ?",
    choices:["Le 23","Le 8","Le 30","Le 1"], correct:0,
    hint:"C'est aussi le numéro que LeBron James a choisi, en hommage à lui.",
    explain:"Le 23 ! Jordan l'a rendu mythique. Beaucoup de joueurs l'ont ensuite porté en son honneur, comme LeBron James." },
  { level:1, theme:"Michael Jordan", rule:"Surnom",
    scene: function(){return sceneMystery("Pourquoi ce surnom ?","#ce1141");},
    q:"Pourquoi appelait-on Michael Jordan « Air Jordan » ?",
    choices:["Parce qu'il avait l'air de voler quand il dunkait","Parce qu'il adorait les avions","Parce qu'il soufflait très fort","Parce qu'il jouait toujours dehors"], correct:0,
    hint:"Regarde ses dunks : il reste très, très longtemps en l'air...",
    explain:"Jordan sautait si haut qu'on avait l'impression qu'il volait. En 1988, il a même dunké en s'envolant depuis la ligne des lancers francs ! Ses chaussures s'appellent aussi « Air Jordan »." },
  { level:1, theme:"Michael Jordan", rule:"Autre sport",
    scene: function(){return sceneMystery("Une pause surprise","#ce1141");},
    q:"Michael Jordan a arrêté le basket pendant presque deux ans pour essayer un autre sport. Lequel ?",
    choices:["Le baseball","Le football","Le tennis","La natation"], correct:0,
    hint:"Un sport très populaire aux États-Unis, avec une batte et une balle.",
    explain:"En 1993, Jordan est parti jouer au baseball. Puis en 1995, il est revenu aux Bulls avec un message tout simple : « I'm back » (je suis de retour) !" },
  { level:1, theme:"Kobe Bryant", rule:"Surnom",
    scene: function(){return sceneJersey("#552583","#fdb927","24","Un surnom de serpent");},
    q:"Quel était le surnom de Kobe Bryant ?",
    choices:["Black Mamba","King James","L'Alien","Air"], correct:0,
    hint:"C'est un serpent très rapide et très précis... comme mon nom de coach !",
    explain:"Kobe s'était lui-même surnommé « Black Mamba », un serpent rapide et précis. La « mentalité Mamba », c'est travailler dur tous les jours pour devenir meilleur." },
  { level:1, theme:"Kobe Bryant", rule:"L'équipe",
    scene: function(){return sceneMystery("20 saisons, 1 seule équipe","#552583");},
    q:"Kobe Bryant a joué ses 20 saisons en NBA dans une seule équipe. Laquelle ?",
    choices:["Los Angeles Lakers","Chicago Bulls","Boston Celtics","Miami Heat"], correct:0,
    hint:"Une équipe violet et or, à Los Angeles.",
    explain:"Kobe a passé toute sa carrière aux Lakers, de 1996 à 2016, et y a gagné 5 titres. C'est très rare de rester 20 ans dans la même équipe !" },
  { level:1, theme:"Kobe Bryant", rule:"Le maillot",
    scene: function(){return sceneJersey("#552583","#fdb927","?","Deux numéros");},
    q:"Kobe a porté deux numéros différents aux Lakers. Lesquels ?",
    choices:["Le 8 et le 24","Le 23 et le 45","Le 1 et le 2","Le 33 et le 34"], correct:0,
    hint:"Le deuxième, c'est trois fois le premier.",
    explain:"Kobe a porté le 8, puis le 24. Les Lakers ont retiré les DEUX maillots : plus personne ne pourra jamais les porter dans l'équipe." },
  { level:1, theme:"Kobe Bryant", rule:"Record",
    scene: function(){return sceneBoard("??","POINTS EN UN MATCH","Match de 2006");},
    q:"En 2006, Kobe a marqué un nombre de points incroyable en un seul match. Combien ?",
    choices:["81 points","50 points","100 points","25 points"], correct:0,
    hint:"C'est plus de 80, mais moins de 100.",
    explain:"81 points contre les Toronto Raptors ! C'est le 2e plus gros score de l'histoire de la NBA en un match, derrière les 100 points de Wilt Chamberlain." },
  { level:1, theme:"Kobe Bryant", rule:"Surprise",
    scene: function(){return sceneTrophy("Un trophée pas comme les autres");},
    q:"En 2018, Kobe a gagné une récompense très surprenante pour un basketteur. Laquelle ?",
    choices:["Un Oscar du cinéma","Une médaille de natation","Le Tour de France","Un prix de cuisine"], correct:0,
    hint:"C'est le prix le plus célèbre du cinéma.",
    explain:"Kobe a écrit un poème pour dire au revoir au basket, « Dear Basketball ». Il a été transformé en court dessin animé... qui a gagné un Oscar !" },
  { level:1, theme:"Wilt Chamberlain", rule:"Record",
    scene: function(){return sceneBoard("100","POINTS EN UN MATCH","Le record absolu");},
    q:"Qui détient le record absolu de 100 points marqués en un seul match NBA ?",
    choices:["Wilt Chamberlain","Michael Jordan","LeBron James","Stephen Curry"], correct:0,
    hint:"Un géant des années 1960, bien avant Jordan.",
    explain:"Wilt Chamberlain a marqué 100 points en 1962. Plus de 60 ans après, personne n'a fait mieux !" },
  { level:1, theme:"Magic Johnson", rule:"Surnom",
    scene: function(){return sceneJersey("#552583","#fdb927","32","Magic");},
    q:"Pourquoi Earvin Johnson était-il surnommé « Magic » ?",
    choices:["Pour ses passes et son jeu incroyables","Parce qu'il faisait des tours de magie","Parce qu'il disparaissait du terrain","Parce qu'il avait une baguette"], correct:0,
    hint:"Sur le terrain, ses passes semblaient impossibles.",
    explain:"Un journaliste l'a surnommé « Magic » quand il avait 15 ans, après un match fou. Meneur de 2,06 m, il faisait des passes magiques et a gagné 5 titres avec les Lakers." },
  { level:1, theme:"Larry Bird", rule:"La rivalité",
    scene: function(){return sceneVersus("#007a33","#552583","La grande rivalité");},
    q:"Larry Bird, le grand rival de Magic Johnson, jouait dans quelle équipe ?",
    choices:["Boston Celtics","Los Angeles Lakers","Chicago Bulls","New York Knicks"], correct:0,
    hint:"Une équipe en vert, avec un trèfle.",
    explain:"Bird jouait aux Boston Celtics (en vert) et Magic aux Lakers (en violet et or). Leur rivalité dans les années 1980 a rendu la NBA célèbre dans le monde entier." },
  { level:1, theme:"Shaquille O'Neal", rule:"Le géant",
    scene: function(){return sceneHoop("Attention au panneau !");},
    q:"Shaquille O'Neal, surnommé « Shaq », était célèbre pour...",
    choices:["Sa force énorme : il a même cassé des panneaux en dunkant","Ses tirs à 3 points","Sa toute petite taille","Ses lancers francs parfaits"], correct:0,
    hint:"Il mesurait 2,16 m et pesait plus de 140 kg !",
    explain:"Shaq était si fort qu'il a cassé des panneaux de basket en dunkant ! Il a gagné 4 titres. Petit secret : il ratait souvent ses lancers francs." },
  { level:1, theme:"Kareem Abdul-Jabbar", rule:"Le tir",
    scene: function(){return sceneHoop("Un tir impossible à contrer",true);},
    q:"Kareem Abdul-Jabbar avait un tir spécial, presque impossible à contrer. Comment s'appelle-t-il ?",
    choices:["Le skyhook (le crochet du ciel)","Le tir du milieu du terrain","Le lancer à la cuillère","Le tir les yeux fermés"], correct:0,
    hint:"Un grand geste du bras, loin au-dessus de la tête, comme un crochet.",
    explain:"Le « skyhook » : bras tendu très haut, le ballon part au-dessus de tout le monde. Grâce à lui, Kareem a été le meilleur marqueur de l'histoire pendant 39 ans !" },

  /* ===================== LES STARS D'AUJOURD'HUI ===================== */
  { level:2, theme:"LeBron James", rule:"Surnom",
    scene: function(){return sceneJersey("#552583","#fdb927","23","Un surnom royal");},
    q:"Quel est le surnom de LeBron James ?",
    choices:["King James (le Roi)","Black Mamba","L'Alien","Air"], correct:0,
    hint:"Un roi porte une couronne...",
    explain:"On l'appelle « King James », le Roi James. Il est considéré comme l'un des plus grands joueurs de tous les temps, avec Jordan." },
  { level:2, theme:"LeBron James", rule:"Record",
    scene: function(){return sceneBoard("40 000","POINTS EN CARRIÈRE","Un record historique");},
    q:"En 2023, LeBron James a battu un record énorme. Lequel ?",
    choices:["Il est devenu le meilleur marqueur de toute l'histoire de la NBA","Il est devenu le plus grand joueur","Il a fait 50 dunks dans un match","Il est devenu le plus jeune joueur"], correct:0,
    hint:"Il a dépassé Kareem Abdul-Jabbar, qui avait ce record depuis 1984.",
    explain:"LeBron est devenu le meilleur marqueur de l'histoire de la NBA, puis le premier à dépasser 40 000 points en carrière !" },
  { level:2, theme:"LeBron James", rule:"En famille",
    scene: function(){return sceneMystery("Une première en NBA","#552583");},
    q:"En 2024, LeBron a fait quelque chose qu'aucun joueur n'avait jamais fait en NBA. Quoi ?",
    choices:["Jouer dans la même équipe que son fils","Jouer avec son chien","Jouer pieds nus","Jouer contre Michael Jordan"], correct:0,
    hint:"Son fils s'appelle Bronny.",
    explain:"LeBron et son fils Bronny James ont joué ensemble aux Lakers : le tout premier duo père-fils sur le terrain en NBA !" },
  { level:2, theme:"LeBron James", rule:"Les titres",
    scene: function(){return sceneTrophy("Combien de bagues ?");},
    q:"Combien de titres de champion NBA LeBron James a-t-il gagnés avec Miami, Cleveland et Los Angeles ?",
    choices:["4","1","8","0"], correct:0,
    hint:"2 avec Miami, 1 avec Cleveland, 1 avec Los Angeles.",
    explain:"4 titres : 2012 et 2013 avec le Miami Heat, 2016 avec les Cleveland Cavaliers, et 2020 avec les Lakers. Et à chaque fois, il a été le meilleur joueur des Finales !" },
  { level:2, theme:"Stephen Curry", rule:"Sa spécialité",
    scene: function(){return sceneJersey("#1d428a","#ffc72c","30","Chef Curry");},
    q:"Stephen Curry est surtout célèbre pour...",
    choices:["Ses tirs à 3 points, même de très loin","Ses dunks géants","Ses contres","Sa taille de géant"], correct:0,
    hint:"Il tire parfois presque depuis le milieu du terrain !",
    explain:"Curry est le meilleur shooteur à 3 points de l'histoire : il en a marqué plus que n'importe qui. Il a changé la façon de jouer au basket !" },
  { level:2, theme:"Stephen Curry", rule:"L'équipe",
    scene: function(){return sceneMystery("Une seule équipe depuis 2009","#1d428a");},
    q:"Dans quelle équipe Stephen Curry a-t-il gagné tous ses titres ?",
    choices:["Golden State Warriors","Chicago Bulls","Boston Celtics","San Antonio Spurs"], correct:0,
    hint:"Une équipe bleu et jaune, près de San Francisco.",
    explain:"Curry joue aux Golden State Warriors depuis 2009. Il y a gagné 4 titres : 2015, 2017, 2018 et 2022." },
  { level:2, theme:"Stephen Curry", rule:"En famille",
    scene: function(){return sceneJersey("#1d428a","#ffc72c","30","Le numéro de papa");},
    q:"Pourquoi Stephen Curry porte-t-il le numéro 30 ?",
    choices:["C'était le numéro de son papa, qui jouait aussi en NBA","C'est son âge","Il est né un 30","Au hasard"], correct:0,
    hint:"Son père, Dell Curry, était aussi un très bon shooteur.",
    explain:"Son père Dell Curry a joué 16 saisons en NBA avec le 30. Stephen a repris le numéro de son papa !" },
  { level:2, theme:"Giannis", rule:"Surnom",
    scene: function(){return sceneJersey("#00471b","#eee1c6","34","Un phénomène venu de Grèce");},
    q:"Quel est le surnom de Giannis Antetokounmpo ?",
    choices:["Greek Freak (le phénomène grec)","King James","Chef Curry","Le Joker"], correct:0,
    hint:"Il vient de Grèce et fait des choses incroyables.",
    explain:"On l'appelle « Greek Freak ». Il a grandi en Grèce et a gagné le titre NBA en 2021 avec les Milwaukee Bucks." },
  { level:2, theme:"Nikola Jokic", rule:"Son pays",
    scene: function(){return sceneGlobe("D'où vient le Joker ?");},
    q:"Nikola Jokic, surnommé « le Joker », vient de quel pays ?",
    choices:["La Serbie","Les États-Unis","La France","Le Canada"], correct:0,
    hint:"Un pays d'Europe, dans les Balkans.",
    explain:"Jokic est serbe. Avec les Denver Nuggets, il a gagné le titre en 2023 et il a été élu plusieurs fois MVP, le meilleur joueur de la saison." },
  { level:2, theme:"Nikola Jokic", rule:"Sa passion",
    scene: function(){return sceneMystery("La passion du Joker","#0e2240");},
    q:"En dehors du basket, quelle est la grande passion de Nikola Jokic ?",
    choices:["Les chevaux","Les voitures de course","Les dinosaures","La danse"], correct:0,
    hint:"Des animaux qui galopent !",
    explain:"Jokic adore les chevaux, surtout les courses de trot. Il en possède plusieurs en Serbie !" },
  { level:2, theme:"Luka Doncic", rule:"Son pays",
    scene: function(){return sceneGlobe("D'où vient Luka ?");},
    q:"Luka Doncic vient de quel pays ?",
    choices:["La Slovénie","L'Espagne","L'Italie","L'Australie"], correct:0,
    hint:"Un petit pays d'Europe, entre l'Italie et la Croatie.",
    explain:"Luka est slovène. Il a commencé chez les pros au Real Madrid à seulement 16 ans avant de devenir une star de la NBA." },
  { level:2, theme:"Titre 2025", rule:"Les champions",
    scene: function(){return sceneTrophy("Les champions 2025");},
    q:"En 2025, Shai Gilgeous-Alexander a été champion NBA et MVP. Avec quelle équipe ?",
    choices:["Oklahoma City Thunder","Los Angeles Lakers","Boston Celtics","Chicago Bulls"], correct:0,
    hint:"Le nom de l'équipe veut dire « le tonnerre ».",
    explain:"Le Thunder d'Oklahoma City a gagné son premier titre en 2025. Shai, un Canadien, a été élu meilleur joueur de la saison ET des Finales !" },
  { level:2, theme:"Kevin Durant", rule:"Les JO",
    scene: function(){return sceneTrophy("Médailles d'or");},
    q:"Kevin Durant détient un record aux Jeux olympiques. Combien de médailles d'or a-t-il gagnées ?",
    choices:["4","1","2","10"], correct:0,
    hint:"Londres, Rio, Tokyo et Paris...",
    explain:"Durant a gagné l'or en 2012, 2016, 2020 et 2024 : c'est le seul basketteur avec 4 médailles d'or olympiques !" },

  /* ===================== LES FRANÇAIS EN NBA ===================== */
  { level:3, theme:"Wembanyama", rule:"Surnom",
    scene: function(){return sceneJersey("#1b1b1b","#c4ced4","1","Venu d'une autre planète ?");},
    q:"Quel est le surnom de Victor Wembanyama ?",
    choices:["L'Alien","Le Roi","Air","Mamba"], correct:0,
    hint:"On dit qu'il vient d'une autre planète tellement il est grand ET agile !",
    explain:"C'est LeBron James qui l'a décrit comme un « alien » : un géant qui dribble et tire comme un petit. Le surnom lui est resté !" },
  { level:3, theme:"Wembanyama", rule:"L'équipe",
    scene: function(){return sceneJersey("#1b1b1b","#c4ced4","?","Noir et argent, au Texas");},
    q:"Dans quelle équipe NBA joue Victor Wembanyama ?",
    choices:["San Antonio Spurs","Los Angeles Lakers","Chicago Bulls","Paris Basketball"], correct:0,
    hint:"Une équipe du Texas, en noir et argent... comme Tony Parker avant lui !",
    explain:"Wemby joue aux San Antonio Spurs, l'équipe où Tony Parker et Boris Diaw ont été champions." },
  { level:3, theme:"Wembanyama", rule:"La draft",
    scene: function(){return sceneBoard("#?","DRAFT 2023","Le choix des équipes");},
    q:"À la draft 2023 (quand les équipes choisissent les nouveaux joueurs), en quelle position Wemby a-t-il été choisi ?",
    choices:["Numéro 1, le tout premier","Numéro 10","Numéro 30","Il n'a pas été choisi"], correct:0,
    hint:"Tout le monde le voulait !",
    explain:"Wemby a été le tout premier choix de la draft 2023. Toutes les équipes rêvaient de l'avoir." },
  { level:3, theme:"Wembanyama", rule:"Le maillot",
    scene: function(){return sceneJersey("#1b1b1b","#c4ced4","?","Quel numéro ?");},
    q:"Quel numéro porte Wemby aux Spurs ?",
    choices:["Le 1","Le 23","Le 24","Le 9"], correct:0,
    hint:"Premier choix de la draft... premier numéro !",
    explain:"Wemby porte le numéro 1." },
  { level:3, theme:"Wembanyama", rule:"Sa taille",
    scene: function(){return sceneHoop("Combien mesure-t-il ?");},
    q:"Environ combien mesure Victor Wembanyama ?",
    choices:["Plus de 2,20 m","1,80 m","2 m pile","3 m"], correct:0,
    hint:"Il est plus grand que la plupart des portes !",
    explain:"Wemby mesure environ 2,24 m. Et quand il écarte les bras, ça fait plus de 2,40 m ! Il peut presque toucher le panier sans sauter." },
  { level:3, theme:"Wembanyama", rule:"Rookie",
    scene: function(){return sceneTrophy("Sa première saison");},
    q:"En 2024, après sa toute première saison en NBA, quel trophée Wemby a-t-il gagné ?",
    choices:["Rookie de l'année (meilleur débutant)","Champion NBA","Meilleur coach","Meilleur arbitre"], correct:0,
    hint:"« Rookie », ça veut dire débutant.",
    explain:"Wemby a été élu Rookie de l'année 2024, le meilleur débutant... et TOUS les votants l'ont choisi !" },
  { level:3, theme:"Wembanyama", rule:"Sa passion",
    scene: function(){return sceneChess("Un cerveau de champion");},
    q:"En dehors du basket, Wemby adore un jeu de réflexion. Lequel ?",
    choices:["Les échecs","Les billes","Le loto","Le Monopoly"], correct:0,
    hint:"Un jeu avec un roi, une reine et des cavaliers.",
    explain:"Wemby adore les échecs ! En 2024, il est même allé défier des joueurs dans un parc de New York." },
  { level:3, theme:"Équipe de France", rule:"JO Paris 2024",
    scene: function(){return sceneTrophy("Paris 2024");},
    q:"Aux Jeux olympiques de Paris 2024, quelle médaille l'équipe de France de Wemby a-t-elle gagnée ?",
    choices:["L'argent","L'or","Le bronze","Aucune"], correct:0,
    hint:"Ils ont perdu la finale contre les États-Unis de LeBron et Curry.",
    explain:"La France a gagné la médaille d'argent ! En finale, elle a perdu contre les États-Unis, avec LeBron James, Stephen Curry et Kevin Durant." },
  { level:3, theme:"Tony Parker", rule:"Les titres",
    scene: function(){return sceneJersey("#c4ced4","#000000","9","Tony Parker");},
    q:"Combien de titres NBA le Français Tony Parker a-t-il gagnés avec les San Antonio Spurs ?",
    choices:["4","1","0","10"], correct:0,
    hint:"2003, 2005, 2007, 2014...",
    explain:"Tony Parker a gagné 4 titres. En 2007, il a été élu meilleur joueur des Finales : le premier Européen à y arriver !" },
  { level:3, theme:"Boris Diaw", rule:"Champion 2014",
    scene: function(){return sceneTrophy("Champions 2014");},
    q:"En 2014, quel autre Français était champion NBA avec Tony Parker aux Spurs ?",
    choices:["Boris Diaw","Kylian Mbappé","Antoine Griezmann","Teddy Riner"], correct:0,
    hint:"Les autres sont des champions... mais d'autres sports !",
    explain:"Boris Diaw, un très bon passeur, a été champion en 2014 avec Tony Parker. Mbappé et Griezmann jouent au foot, Teddy Riner fait du judo !" },
  { level:3, theme:"Rudy Gobert", rule:"La défense",
    scene: function(){return sceneHoop("Personne ne passe !");},
    q:"Le Français Rudy Gobert est surtout célèbre pour...",
    choices:["Ses contres et sa défense","Ses tirs à 3 points","Être le plus petit joueur","Ses dribbles entre les jambes"], correct:0,
    hint:"Il est surnommé « Stifle Tower », un jeu de mots avec la Tour Eiffel !",
    explain:"Gobert a été élu 4 fois meilleur défenseur de la NBA : un record ! Avec ses grands bras, il contre tout ce qui passe." },
  { level:3, theme:"Draft 2024", rule:"Encore un Français",
    scene: function(){return sceneBoard("#1","DRAFT 2024","Encore un Français !");},
    q:"En 2024, un an après Wemby, un autre Français a été choisi en numéro 1 de la draft. Qui ?",
    choices:["Zaccharie Risacher","Tony Parker","Rudy Gobert","Kylian Mbappé"], correct:0,
    hint:"Il a été choisi par les Atlanta Hawks.",
    explain:"Zaccharie Risacher a été choisi numéro 1 par les Atlanta Hawks, et un autre Français, Alex Sarr, numéro 2 ! La France est devenue un pays de champions du basket." },
  { level:3, theme:"Wembanyama", rule:"Avant la NBA",
    scene: function(){return sceneMystery("Avant de partir aux États-Unis","#0055a4");},
    q:"Avant la NBA, dans quel club Wemby jouait-il en France ?",
    choices:["Les Metropolitans 92 (Boulogne-Levallois)","Le Real Madrid","Les Chicago Bulls","Le PSG football"], correct:0,
    hint:"Un club de la région parisienne, dans les Hauts-de-Seine (92).",
    explain:"Wemby a commencé à Nanterre, puis il a joué à l'ASVEL et enfin aux Metropolitans 92, où il a été élu meilleur joueur du championnat de France." },

  /* ===================== LA NBA ===================== */
  { level:4, theme:"La ligue", rule:"Les équipes",
    scene: function(){return sceneVersus("#c8102e","#1d428a","Combien d'équipes ?");},
    q:"Combien y a-t-il d'équipes en NBA ?",
    choices:["30","10","50","100"], correct:0,
    hint:"29 aux États-Unis et 1 au Canada.",
    explain:"Il y a 30 équipes : 29 aux États-Unis et 1 au Canada (les Toronto Raptors)." },
  { level:4, theme:"La ligue", rule:"Le Canada",
    scene: function(){return sceneGlobe("Une seule hors des États-Unis");},
    q:"Quelle est la seule équipe NBA qui joue au Canada ?",
    choices:["Toronto Raptors","Chicago Bulls","Miami Heat","New York Knicks"], correct:0,
    hint:"Leur mascotte est un dinosaure !",
    explain:"Les Toronto Raptors (raptor = un dinosaure) jouent au Canada. Ils ont été champions en 2019." },
  { level:4, theme:"Les règles", rule:"Le temps",
    scene: function(){return sceneClock("12","Un quart-temps");},
    q:"Un match NBA dure 4 quarts-temps. Combien de minutes dure chaque quart-temps ?",
    choices:["12 minutes","10 minutes","20 minutes","45 minutes"], correct:0,
    hint:"C'est un peu plus long qu'en France, où c'est 10 minutes.",
    explain:"En NBA, chaque quart-temps dure 12 minutes, donc 48 minutes en tout. En France et en Europe, c'est 4 fois 10 minutes." },
  { level:4, theme:"Les règles", rule:"Les 24 secondes",
    scene: function(){return sceneClock("??","Vite, il faut tirer !");},
    q:"En NBA, combien de secondes une équipe a-t-elle pour tirer au panier ?",
    choices:["24 secondes","10 secondes","60 secondes","5 secondes"], correct:0,
    hint:"Deux douzaines de secondes.",
    explain:"Une équipe a 24 secondes pour tirer. Sinon, le ballon va à l'adversaire. C'est pour que le jeu reste rapide !" },
  { level:4, theme:"Les règles", rule:"Les fautes",
    scene: function(){return sceneBoard("?","FAUTES PERSONNELLES","Trop de fautes...");},
    q:"En NBA, au bout de combien de fautes un joueur doit-il quitter le match ?",
    choices:["6 fautes","5 fautes","3 fautes","10 fautes"], correct:0,
    hint:"Une de plus qu'en France !",
    explain:"En NBA, un joueur sort à sa 6e faute. En France et en Europe, c'est à la 5e faute." },
  { level:4, theme:"Le panier", rule:"La hauteur",
    scene: function(){return sceneHoop("À quelle hauteur ?");},
    q:"À quelle hauteur est le panier en NBA ?",
    choices:["3,05 m","2,60 m","4 m","2 m"], correct:0,
    hint:"C'est la même hauteur que pour les grands en France.",
    explain:"Le panier est à 3,05 m du sol, comme partout chez les adultes. En mini-basket, il est à 2,60 m." },
  { level:4, theme:"Les Finales", rule:"Le format",
    scene: function(){return sceneVersus("#007a33","#552583","Les Finales NBA");},
    q:"Pour gagner les Finales NBA, combien de matchs faut-il gagner ?",
    choices:["4 matchs (le premier à 4 victoires)","1 seul match","2 matchs","10 matchs"], correct:0,
    hint:"On joue au maximum 7 matchs.",
    explain:"Les Finales se jouent « au meilleur des 7 matchs » : la première équipe qui gagne 4 matchs est championne." },
  { level:4, theme:"Les trophées", rule:"Le champion",
    scene: function(){return sceneTrophy("Le trophée des champions");},
    q:"Comment s'appelle le trophée remis à l'équipe championne NBA ?",
    choices:["Le trophée Larry O'Brien","La Coupe du monde","Le Ballon d'or","La Ligue des champions"], correct:0,
    hint:"Il porte le nom d'un ancien patron de la NBA.",
    explain:"C'est le trophée Larry O'Brien : un gros ballon doré posé sur un panier. Les joueurs reçoivent aussi une bague de champion !" },
  { level:4, theme:"Les trophées", rule:"MVP",
    scene: function(){return sceneTrophy("M.V.P.");},
    q:"Que veut dire « MVP » ?",
    choices:["Le joueur le plus précieux : le meilleur de la saison","Un type de dunk","Une faute grave","Le nom d'une équipe"], correct:0,
    hint:"En anglais : Most Valuable Player.",
    explain:"MVP = Most Valuable Player, le joueur le plus précieux. Chaque année, le meilleur joueur de la saison reçoit ce trophée." },
  { level:4, theme:"Les stats", rule:"Triple-double",
    scene: function(){return sceneBoard("10-10-10","POINTS - REBONDS - PASSES","Le triple-double");},
    q:"Qu'est-ce qu'un « triple-double » ?",
    choices:["Au moins 10 dans trois catégories (points, rebonds, passes...)","Trois dribbles d'affilée","Un tir qui vaut 6 points","Trois fautes en même temps"], correct:0,
    hint:"Regarde le tableau d'affichage : 10, 10 et 10 !",
    explain:"Un triple-double, c'est faire au moins 10 dans trois statistiques en un match : par exemple 10 points, 10 rebonds et 10 passes. Jokic et Westbrook sont des champions de ça !" },
  { level:4, theme:"L'histoire", rule:"Les plus titrés",
    scene: function(){return sceneVersus("#007a33","#552583","Les rois des titres");},
    q:"Quelles sont les deux équipes qui ont gagné le plus de titres dans l'histoire de la NBA ?",
    choices:["Les Boston Celtics et les Los Angeles Lakers","Les Chicago Bulls et les Miami Heat","Les Spurs et les Raptors","Les Knicks et les Warriors"], correct:0,
    hint:"Une équipe verte et une équipe violet et or.",
    explain:"Les Celtics et les Lakers ont chacun gagné 17 titres ou plus. C'est la plus grande rivalité de la NBA !" },
  { level:4, theme:"Les équipes", rule:"Les Bulls",
    scene: function(){return sceneAnimal("Quel animal ?");},
    q:"Quel animal représente les Chicago Bulls, l'équipe de Michael Jordan ?",
    choices:["Un taureau","Un ours","Un aigle","Un lion"], correct:0,
    hint:"« Bull », en anglais, c'est un animal avec des cornes.",
    explain:"« Bull » veut dire taureau. Leur logo est une tête de taureau rouge !" },
  { level:4, theme:"L'All-Star Game", rule:"Le concours",
    scene: function(){return sceneHoop("Le concours de dunks");},
    q:"Pendant quel événement a lieu le célèbre concours de dunks ?",
    choices:["Le All-Star Game (le match des étoiles)","Les Finales","Noël","Les Jeux olympiques"], correct:0,
    hint:"Un week-end de fête où les meilleurs joueurs sont invités.",
    explain:"Chaque année, pendant le week-end du All-Star Game, les stars font un match de gala, un concours de dunks et un concours de tirs à 3 points !" },
  { level:4, theme:"La draft", rule:"Les jeunes",
    scene: function(){return sceneBoard("#1","LA DRAFT","Choisir les jeunes");},
    q:"Qu'est-ce que la « draft » en NBA ?",
    choices:["Le moment où les équipes choisissent les jeunes joueurs","Un match de gala","Une faute technique","Une danse de victoire"], correct:0,
    hint:"Wemby a été le numéro 1 de celle de 2023.",
    explain:"La draft, c'est chaque été : les équipes choisissent chacune leur tour les meilleurs jeunes joueurs du monde. Les équipes les moins fortes ont souvent plus de chances de choisir en premier." }
];

/* Bonus culture basket (pour le fun, ne compte pas) */
var BONUS=[
 {q:"Qui a inventé le basket-ball, en 1891 ?",choices:["Un professeur de sport, James Naismith","Michael Jordan","Un roi anglais","Personne, il a toujours existé"],correct:0,explain:"Le basket a été inventé en 1891 par James Naismith, un professeur, pour occuper ses élèves pendant l'hiver."},
 {q:"Au tout début, dans quoi marquait-on les paniers ?",choices:["Un vrai panier de basket","Un panier de pêches accroché au balcon","Un seau en métal","Un filet de foot"],correct:1,explain:"Au début, on visait un panier de pêches ! Il fallait aller rechercher le ballon à chaque panier marqué."},
 {q:"Dans quel film Michael Jordan joue-t-il au basket avec Bugs Bunny ?",choices:["Space Jam","Toy Story","Cars","Le Roi Lion"],correct:0,explain:"Space Jam (1996) ! Et en 2021, LeBron James a joué dans Space Jam 2."},
 {q:"En 1992, l'équipe des États-Unis avec Jordan, Magic et Bird avait un surnom. Lequel ?",choices:["La Dream Team (l'équipe de rêve)","Les Avengers","La Super Team","Les Invincibles"],correct:0,explain:"La Dream Team des Jeux de Barcelone 1992, peut-être la meilleure équipe de l'histoire !"},
 {q:"Comment s'appelle le panier où le ballon rentre sans toucher l'anneau ?",choices:["Un swish","Un plouf","Un boing","Un splash"],correct:0,explain:"« Swish » ! C'est le bruit du ballon qui ne touche que le filet."}
];

/* ============================================================
   COACH  (personnage inspiré de Kobe Bryant)
   >>> Tu peux changer le nom ci-dessous : il apparaîtra partout.
   ============================================================ */
var COACH_NAME="Coach Mamba";
var SECRETS=[
 "Kobe arrivait à l'entraînement bien avant tout le monde. Le secret des champions : travailler même quand personne ne regarde.",
 "Kobe regardait les vidéos de ses matchs pour trouver ses erreurs. Rater, ce n'est pas grave : c'est comme ça qu'on apprend !",
 "Pour dribbler comme un pro : tête haute ! Regarde tes coéquipiers, pas le ballon.",
 "Stephen Curry s'échauffe en dribblant avec DEUX ballons en même temps. Essaie avec un seul d'abord !",
 "Quand tu tires : le coude sous le ballon, et à la fin, laisse ta main « dans le panier », comme si tu attrapais un biscuit dans un pot.",
 "Jordan n'a pas été pris dans la grande équipe de son lycée la première fois. Il s'est entraîné encore plus... et tu connais la suite !",
 "LeBron James dort beaucoup pour être en forme. Le sommeil, c'est l'arme secrète des champions.",
 "Wemby joue aux échecs pour muscler son cerveau. Au basket aussi, il faut réfléchir vite !",
 "Un bon joueur de basket fait des passes. Le meilleur panier, c'est souvent celui de ton coéquipier démarqué.",
 "Au lancer franc, fais toujours le même petit rituel avant de tirer : ça calme et ça aide à viser."
];
var GOOD=["Tu as la mentalité Mamba !","Rien que le filet.","Magnifique ! Même Wemby applaudit.","Tu voles comme Air Jordan !","Digne de Chef Curry !","Le Roi James serait fier de toi !","Bonne réponse, "+COACH_NAME+" valide !"];
var BAD=["Raté... mais un champion se relève toujours. On y retourne !","Kobe a raté des milliers de tirs avant de devenir une légende. À toi de rebondir !","Le ballon a tourné puis ressorti. Pas grave, on remet ça !","Contré par la défense ! On respire et on repart.","Pas cette fois. Retiens bien la réponse, elle reviendra !"];

/* ============================================================
   JOUEURS : personnages inventés (seul Coach Mamba est inspiré
   d'un vrai joueur, Kobe Bryant). tag = sa petite histoire.
   ============================================================ */
var PLAYERS=[
 {id:'p1',name:'Cosmo',       tag:"Venu d'une autre galaxie : ses tirs partent en orbite.",          num:'42', c1:'#3d2470',c2:'#d9dde6',skin:'#8a5a3a',hair:'curly',need:0},
 {id:'p2',name:'Roi Rebond',  tag:"Aucun rebond ne lui échappe : la raquette, c'est son royaume.",   num:'11', c1:'#f2b01e',c2:'#552583',skin:'#6b4226',hair:'band', need:0},
 {id:'p3',name:'Jet',         tag:"Il décolle comme un avion et plane jusqu'au panier.",             num:'5',  c1:'#2a7de1',c2:'#ffffff',skin:'#5a3620',hair:'bald', need:0},
 {id:'p4',name:'Chef Swish',  tag:"Il cuisine des tirs à 3 points et les sert tout chauds.",         num:'3',  c1:'#e8752a',c2:'#1b1733',skin:'#a8724a',hair:'short',need:0},
 {id:'p5',name:'Olympe',      tag:"Le champion des Jeux : il ne vise que la médaille d'or.",         num:'12', c1:'#0f7c78',c2:'#eee1c6',skin:'#5e3b22',hair:'short',need:3},
 {id:'p6',name:'Le Magicien', tag:"Ses passes sortent de sa manche comme des cartes magiques.",      num:'7',  c1:'#6fb52c',c2:'#5b2a86',skin:'#f1c9a5',hair:'brown',need:6},
 {id:'p7',name:'Lightning',   tag:"Rapide comme l'éclair : personne ne le rattrape en contre-attaque.", num:'10', c1:'#1e3f9a',c2:'#ffffff',skin:'#9a6a45',hair:'short',need:9},
 {id:'p8',name:'Dunkman',     tag:"Le plus costaud de la ligue : il casse tous les paniers !",       num:'50', c1:'#d0202e',c2:'#ffffff',skin:'#4a2c18',hair:'bald', need:12}
];
