/* ============================================================
   NIVEAU PRO (level 6) : questions plus difficiles
   - +5 points par bonne réponse (+10 en série « En feu »)
   - l'indice coûte 2 points et il est plus vague
   - hors du « Match des étoiles »
   ============================================================ */
var PRO_POINTS=5, PRO_HINT_COST=2;
var PRO_BANK=[
  /* ---------- Combinaisons et tactique ---------- */
  { theme:"Tactique", rule:"Combinaison",
    scene:function(){return RA.sceneContact('Le bloc');},
    q:"Un coéquipier vient se planter contre ton défenseur pour le bloquer, puis il file vers le panier pour recevoir ta passe. Comment s'appelle cette combinaison ?",
    choices:["Le pick and roll (écran et roulé)","Le fast break","La zone press","Le box-out"], correct:0,
    hint:"En anglais, « pick » c'est l'écran, « roll » c'est rouler vers le panier.",
    explain:"C'est le pick and roll : l'écran bloque ton défenseur, puis le poseur d'écran « roule » vers le panier. C'est la combinaison la plus utilisée en NBA." },
  { theme:"Tactique", rule:"Combinaison",
    scene:function(){return sceneVersus('#1d428a','#c8102e','Passe et va');},
    q:"Tu passes le ballon à un coéquipier, tu coupes tout de suite vers le panier et il te le redonne. C'est...",
    choices:["Le « passe et va » (give and go)","Un marcher","Une remise en jeu","Un retour en zone"], correct:0,
    hint:"Tu donnes... et tu pars.",
    explain:"Le « passe et va » (give and go en anglais) : on passe, on coupe vers le panier, on reçoit à nouveau. Simple et redoutable !" },
  { theme:"Tactique", rule:"Alley-oop",
    scene:function(){return sceneHoop('Alley-oop !');},
    q:"Dans un alley-oop, que fait le joueur qui reçoit la passe ?",
    choices:["Il attrape le ballon en l'air et le met dans le panier avant de retomber","Il dribble trois fois puis tire","Il attend le rebond","Il tire un lancer franc"], correct:0,
    hint:"Tout se passe en plein vol.",
    explain:"L'alley-oop : un coéquipier lance le ballon près du cercle, et le joueur l'attrape en plein saut pour dunker ou déposer le ballon avant de toucher le sol." },
  { theme:"Tactique", rule:"L'écran",
    scene:function(){return RA.sceneContact('Écran en mouvement');},
    q:"Le joueur qui pose l'écran bouge au moment où le défenseur arrive et le percute. L'arbitre siffle...",
    choices:["Une faute offensive (écran illégal)","Rien, c'est permis","Une faute du défenseur","Un ballon tenu"], correct:0,
    hint:"Un bon écran, c'est comme un poteau.",
    explain:"Un écran doit être immobile. S'il bouge au moment du contact, c'est un écran illégal : faute de l'attaquant qui pose l'écran." },
  { theme:"Tactique", rule:"Coupe",
    scene:function(){return RA.sceneDefIndiv();},
    q:"Ton défenseur te colle de trop près pour t'empêcher de recevoir. Tu pars d'un coup dans son dos, vers le panier. Comment s'appelle ce mouvement ?",
    choices:["Un backdoor (coupe dans le dos)","Un pivot","Un double pas","Un écran retard"], correct:0,
    hint:"Par la porte de derrière...",
    explain:"Le backdoor : quand le défenseur est trop collé, on file dans son dos vers le panier. Il suffit d'une bonne passe pour marquer facilement." },
  { theme:"Tactique", rule:"Le rebond",
    scene:function(){return sceneHoop('Au rebond');},
    q:"Au moment du tir, tu te places dos à ton adversaire, entre lui et le panier, pour prendre le rebond. Comment appelle-t-on ce geste ?",
    choices:["Le box-out (écran au rebond)","Le crossover","Le fadeaway","Le sky hook"], correct:0,
    hint:"Tu lui fermes la porte avec ton dos.",
    explain:"Le box-out (ou écran au rebond) : on se place entre l'adversaire et le panier. Les meilleurs rebondeurs ne sautent pas toujours le plus haut, ils sont surtout bien placés !" },
  { theme:"Tactique", rule:"L'attaque en triangle",
    scene:function(){return sceneTrophy('11 titres de coach');},
    q:"Avec quel entraîneur l'« attaque en triangle » a-t-elle gagné des titres aux Bulls de Jordan puis aux Lakers de Kobe ?",
    choices:["Phil Jackson","Gregg Popovich","Pat Riley","Steve Kerr"], correct:0,
    hint:"On le surnommait le « maître zen ».",
    explain:"Phil Jackson a gagné 11 titres comme entraîneur : 6 avec les Bulls de Jordan et 5 avec les Lakers de Kobe et Shaq, grâce à l'attaque en triangle." },
  { theme:"Tactique", rule:"Le dribble",
    scene:function(){return RA.sceneDribble();},
    q:"Tu fais passer le ballon très vite d'une main à l'autre devant toi pour déséquilibrer ton défenseur. C'est...",
    choices:["Un crossover","Un alley-oop","Un tip-in","Un and-one"], correct:0,
    hint:"Le ballon « traverse » devant toi.",
    explain:"Le crossover : un changement de main rapide devant soi. Allen Iverson et Kyrie Irving en ont fait une arme redoutable." },

  /* ---------- Dunks et concours ---------- */
  { theme:"Dunks", rule:"Concours 1988",
    scene:function(){return sceneHoop('Un envol légendaire');},
    q:"En 1988, Michael Jordan gagne le concours de dunks avec un dunk mythique. D'où a-t-il décollé ?",
    choices:["De la ligne des lancers francs","Du milieu du terrain","De la ligne à 3 points","Du dessous du panier"], correct:0,
    hint:"C'est à 4,60 m du panneau.",
    explain:"Jordan s'est envolé depuis la ligne des lancers francs, à plus de 4 mètres du panier, pour dunker. Une photo devenue célèbre dans le monde entier !" },
  { theme:"Dunks", rule:"Concours 2000",
    scene:function(){return sceneMystery('Half-man, half-amazing','#ce1141');},
    q:"Quel joueur des Toronto Raptors a gagné le concours de dunks 2000, souvent considéré comme le plus beau de l'histoire ?",
    choices:["Vince Carter","Kobe Bryant","Shaquille O'Neal","Tony Parker"], correct:0,
    hint:"Son surnom : « à moitié homme, à moitié incroyable ».",
    explain:"Vince Carter a éclaboussé le concours 2000 : moulin à 360°, et même un dunk où il a laissé son bras dans le cercle !" },
  { theme:"Dunks", rule:"Petit mais costaud",
    scene:function(){return sceneBoard('1,70 m','TAILLE DU CHAMPION','Concours 1986');},
    q:"En 1986, Spud Webb a gagné le concours de dunks. Qu'avait-il de spécial ?",
    choices:["Il mesurait seulement 1,70 m","Il avait 45 ans","Il dunkait les yeux bandés","Il n'avait jamais joué en NBA"], correct:0,
    hint:"Regarde le tableau.",
    explain:"Spud Webb mesurait 1,70 m, un des plus petits joueurs de la NBA, et il a gagné le concours de dunks face à des géants. La preuve que la détente se travaille !" },
  { theme:"Dunks", rule:"Record",
    scene:function(){return sceneBoard('x3','CONCOURS GAGNÉS','Le petit roi du dunk');},
    q:"Nate Robinson (1,75 m) a gagné le concours de dunks combien de fois ?",
    choices:["3 fois","1 fois","5 fois","10 fois"], correct:0,
    hint:"2006, 2009, 2010...",
    explain:"Nate Robinson a gagné 3 concours de dunks (2006, 2009 et 2010). En 2006, il a même sauté par-dessus Spud Webb !" },
  { theme:"Dunks", rule:"Le duel",
    scene:function(){return sceneVersus('#ce1141','#0077c0','Duel 2016');},
    q:"Le concours de dunks 2016 est resté célèbre pour un duel incroyable entre Zach LaVine et Aaron Gordon. Qui a gagné ?",
    choices:["Zach LaVine","Aaron Gordon","Personne, égalité","Michael Jordan"], correct:0,
    hint:"Il avait déjà gagné l'année d'avant.",
    explain:"Zach LaVine a gagné en 2016 (et déjà en 2015), après plusieurs prolongations de dunks parfaits face à Aaron Gordon." },

  /* ---------- Règles avancées ---------- */
  { theme:"Règles pro", rule:"Faute disqualifiante",
    scene:function(){return RA.sceneTech();},
    q:"Un joueur se bat avec un adversaire. L'arbitre siffle une faute disqualifiante. Que se passe-t-il ?",
    choices:["Il est exclu tout de suite, et l'adversaire a des lancers francs puis le ballon","Il prend juste 1 faute personnelle","Il doit s'asseoir 2 minutes","Rien si personne n'est blessé"], correct:0,
    hint:"C'est la sanction la plus grave.",
    explain:"Faute disqualifiante : le joueur quitte le terrain et ne revient plus. L'adversaire tire des lancers francs et récupère ensuite le ballon." },
  { theme:"Règles pro", rule:"Antisportives",
    scene:function(){return sceneSignal('unsport');},
    q:"En FIBA, au bout de combien de fautes antisportives un joueur est-il exclu du match ?",
    choices:["2","1","3","5"], correct:0,
    hint:"Comme pour les fautes techniques.",
    explain:"Deux fautes antisportives (ou une technique et une antisportive, ou deux techniques) et le joueur est exclu." },
  { theme:"Règles pro", rule:"Prolongation",
    scene:function(){return RA.sceneContact("Fautes d'équipe");},
    q:"Le match va en prolongation. Que deviennent les fautes d'équipe ?",
    choices:["Elles continuent à compter comme au 4e quart-temps","Elles repartent à zéro","Elles sont doublées","On n'en compte plus"], correct:0,
    hint:"La prolongation, c'est comme la suite du dernier quart-temps.",
    explain:"En FIBA, les prolongations comptent comme le 4e quart-temps pour les fautes d'équipe : si l'équipe était déjà « dans le bonus », elle le reste." },
  { theme:"Règles pro", rule:"Goaltending attaquant",
    scene:function(){return RA.sceneGoaltend('rim');},
    q:"Un ATTAQUANT touche le ballon de son coéquipier pendant qu'il redescend au-dessus du cercle, et le ballon rentre. Le panier...",
    choices:["Ne compte pas","Compte double","Compte normalement","Vaut 1 point"], correct:0,
    hint:"La règle marche dans les deux sens.",
    explain:"Toucher le ballon qui redescend au-dessus du cercle est interdit pour tout le monde. Si c'est un attaquant, le panier est refusé et le ballon va à l'adversaire." },
  { theme:"Règles pro", rule:"Lancers francs",
    scene:function(){return RA.sceneFreeThrow();},
    q:"Pendant un lancer franc, à quel moment les joueurs placés le long de la raquette ont-ils le droit d'y entrer ?",
    choices:["Dès que le ballon quitte les mains du tireur","Quand le ballon touche le cercle","Avant le tir","Après le coup de sifflet"], correct:0,
    hint:"Pas besoin d'attendre le cercle... sauf pour le tireur !",
    explain:"Les joueurs au rebond peuvent entrer dans la raquette dès que le ballon a quitté les mains du tireur. Le tireur, lui, doit attendre que le ballon touche le cercle." },
  { theme:"Règles pro", rule:"Temps-morts",
    scene:function(){return sceneSignal('timeout');},
    q:"En FIBA, combien de temps-morts une équipe a-t-elle en deuxième mi-temps ?",
    choices:["3","1","5","Autant qu'elle veut"], correct:0,
    hint:"Un de plus qu'en première mi-temps.",
    explain:"2 temps-morts en première mi-temps, 3 en deuxième (dont 2 au maximum dans les 2 dernières minutes du match), et 1 par prolongation." },
  { theme:"Règles pro", rule:"Zone de non-charge",
    scene:function(){return RA.sceneCharge();},
    q:"Un défenseur se place dans le petit demi-cercle sous le panier et l'attaquant lui fonce dedans. L'arbitre peut-il siffler un passage en force ?",
    choices:["Non : dans le demi-cercle, pas de passage en force","Oui, toujours","Seulement en NBA","Oui, et c'est 3 lancers francs"], correct:0,
    hint:"Ce demi-cercle a un nom : la zone de non-charge.",
    explain:"Le demi-cercle sous le panier est la zone de non-charge : un défenseur qui s'y trouve ne peut pas obtenir de passage en force. Ça évite de « planter » les attaquants qui montent au panier." }
];
(function(){for(var i=0;i<PRO_BANK.length;i++){var q=PRO_BANK[i];q.level=6;BANK.push(q);}})();
LEVELS[6]={name:"Niveau Pro", sub:"Tactiques, dunks, règles avancées · +5 pts par réponse", color:"#1b1733", sym:"PRO", pro:true};
LEVEL_ORDER.push(6);
